## Some properties of Numpy arrays

**data : this gives the address of first element of the array**<br>**shape: gives the dimensions of the array**<br>
**dtype: gives the datatype of the array elements**<br>
**strides : gives the jump**

In [1]:
import numpy as np

a = [1,2,3,4,6,7]
b = np.array(a)

print(a)
print(b)

[1, 2, 3, 4, 6, 7]
[1 2 3 4 6 7]


In [2]:
print(b.data)
print(b.shape)
print(b.dtype)
print(b.strides)

(6,)
int32
(4,)


In [3]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


**Accessing elements of numpy array and slicing**

In [6]:
print(a[3])
print(b[3])

4
4


In [8]:
print(a[1:4])
print(b[1:4])

[2, 3, 4]
[2 3 4]


**Accessing and slicing in 1d array is same in both numpy and normal array**

In [9]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)

In [12]:
print(arr_2d[2][1])
print(li_2d[2][1])
print(arr_2d[2,1])  ## in this way also we can access numpy array which we cant do with normal array

10
10
10


**print(arr_2d[2,1])  ## in this way also we can access numpy array which we cant do with normal array**

**now slicing 2 d array**

In [15]:
print(li_2d[1][0:3])
print(arr_2d[1,0:3]) ## numpy array can work this way while slicing as well

[5, 6, 7]
[5 6 7]


**Above is row wise slicing which works fine in both type arrays**

In [17]:
print(li_2d[0:3][3])  

IndexError: list index out of range

**what ?? how come is there any error because of this: it is because in normal array it first resolves the left part then the right part**

In [19]:
p = li_2d[0:3][2] ## this  should print 3,7 11 by our logic but printing something else
p

[9, 10, 11, 12]

In [20]:
p = li_2d[0:3]
p

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [21]:
print(p[2])

[9, 10, 11, 12]


**So if we look at the steps we can understand that normal array first resolves left then it resolves right over the answer of left**

**So numpy array comes as a saviour for us**

In [22]:
print(arr_2d[0:3,3])  ## voila it worked

[ 4  8 12]


In [24]:
print(li_2d[2:4][1:3]) ## oops it looks like we need to use for loop to do this in normal array

[[13, 14, 15, 16]]


In [26]:
#trying with numpy array now
print(arr_2d[2:4,1:3])   ## yeah we did it

[[10 11]
 [14 15]]


In [60]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)


a = input_[2,:3]
b = input_[1:4,3]
c = input_[2:4,]
d = input_[1:3,1:3]




def print_1darr(arr):
    for i in arr:
        print(i,end = ' ')
    print()
    
def print_2darr(arr,m,n):
    for i in range(m):
        for j in range(n):
            print(arr[i,j],end = ' ')
    print()
            
print_1darr(a)
print_1darr(b)
print_2darr(c,2,5)
print_2darr(d,2,2)


11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 


11 12 13
