In [8]:
import numpy as np

li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)


[1, 2, 3, 4, 5]
[ 9  8  7 16 14]
[ 1  3  3 19 13]


**Lets add 1 to each element of both type of list**

In [9]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [10]:
a = a+ 1
print(a)

[10  9  8 17 15]


**If we want to do element by element addition its very easy in Numpy**

In [13]:
c = a + b
print(c)

[11 12 11 36 28]


In [14]:
d = a - b
print(d)

[ 9  6  5 -2  2]


In [15]:
e = a*b
e

array([ 10,  27,  24, 323, 195])

In [16]:
f = a/b
f

array([10.        ,  3.        ,  2.66666667,  0.89473684,  1.15384615])

In [17]:
g = a//b
g

array([10,  3,  2,  0,  1], dtype=int32)

In [19]:
h = a**b
h

array([        10,        729,        512,  572603441, -642346289],
      dtype=int32)

**Some useful numpy functions we need to know**<br>
**sum()**<br>
**mean()**<br>
**min()**<br>
**max()**<br>
**argmin() : gives the index of minimum number in numpy array**<br>
**argmax() : gives the index of maximum number in numpy array**<br>


In [21]:
print(a)
print('sum: ',a.sum())
print('mean: ',a.mean())
print('max: ',a.max())
print('min: ',a.min())
print('argmin: ',a.argmin())
print('argmax: ',a.argmax())

[10  9  8 17 15]
sum:  59
mean:  11.8
max:  17
min:  8
argmin:  2
argmax:  3


**Lets try all logical and relational operators with numpy arrays**

In [23]:
print(a)
print(b)

[10  9  8 17 15]
[ 1  3  3 19 13]


In [25]:
a > b

array([ True,  True,  True, False,  True])

In [26]:
a < b

array([False, False, False,  True, False])

In [27]:
a == b

array([False, False, False, False, False])

**Following are the relational operators used over numpy arrays:**<br>
**np.logical_and(var1,var2)**<br>
**np.logical_or(var1,var2)**<br>
**np.logical_not(var1)**

In [28]:
print(np.logical_and(a,b))
print(np.logical_or(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [30]:
print(np.logical_not(a))

[False False False False False]


**All are coming as false because in python everything which is non zero is true and zero is false**

In [31]:
a[2] = 0
print(np.logical_not(a))

[False False  True False False]
