In [21]:
import numpy as np

arr = np.random.randint(2,25,6)
print(arr)

[21  3 14 10 14 16]


**Now lets say I want an array of elements which are in arr and greater than 10**

In [22]:
bool_arr = arr > 10
print('bool_arr ',bool_arr)
new_arr  = arr[bool_arr]
print('new array ',new_arr)

bool_arr  [ True False  True False  True  True]
new array  [21 14 14 16]


**what you have seen above is beauty of bool indexing and we can do the same in a single line**

In [23]:
print(arr)
new_arr = arr[arr > 10] ## this is the single line step
print(new_arr)

[21  3 14 10 14 16]
[21 14 14 16]


**We can also club multiple conditions together**

In [24]:
new_arr = arr[(arr > 10) & (arr < 18)]
print(arr)
print(new_arr)

[21  3 14 10 14 16]
[14 14 16]


**We can also update multiple elements together in case of numpy arrays**

In [25]:
print('arr :',arr)
c = arr
c[:2] = 15
print(c)
c[c>11] = 123
print(c)

arr : [21  3 14 10 14 16]
[15 15 14 10 14 16]
[123 123 123  10 123 123]


**Very important function is where(condition): this function returns the indices of all the elements of array which satisfies the condition**

In [27]:
print(arr)
b = np.array(['a','b','c','d','e','f'])
ind_arr = np.where(arr == 123)
print(ind_arr)


[123 123 123  10 123 123]
(array([0, 1, 2, 4, 5], dtype=int64),)


In [29]:
print(b)
print(arr)
out_arr = b[ind_arr]
print(out_arr)

['a' 'b' 'c' 'd' 'e' 'f']
[123 123 123  10 123 123]
['a' 'b' 'c' 'e' 'f']


In [84]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
ind = np.where(arr != 0)
s = str(ind[0])
print(s.strip('[').strip(']'))



AttributeError: 'numpy.ndarray' object has no attribute 'strip'

In [85]:
import numpy as np

a = np.array([1,3,5,7,9,11,13,15,17,19])
ind = np.where(a % 3 == 0)
s = str(ind[0])
print(s.strip('[').strip(']'))



1 4 7


In [89]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a%2 != 0] = -1
for i in a:
    print(i , end = ' ')


-1 2 -1 4 -1 6 -1 8 -1 10 

In [91]:
import numpy as np
a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
a[a.argmax()] = 0
for i in a:
    print(i)

11
2
13
4
15
6
0
8
19


In [107]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ind = np.where((a <= 8) & (a >= 3))
b[ind] = 0
c = b - a
d = c+b
for i in d:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


In [109]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

ind = np.where(height > 155)
age_p = age[ind]
height_p = height[ind]

for i in range(age_p.size):
    print(age_p[i],height_p[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172
