In [10]:
import numpy as np

a = np.random.randint(1,30,(5,6))
a

array([[25, 24, 29, 26, 26, 28],
       [20, 19,  6, 26, 11,  5],
       [ 2, 21, 27,  8,  6, 26],
       [13, 12, 11, 16, 22, 18],
       [12, 25, 12, 13, 28,  6]])

In [11]:
bool_arr = a > 20
print(bool_arr)

[[ True  True  True  True  True  True]
 [False False False  True False False]
 [False  True  True False False  True]
 [False False False False  True False]
 [False  True False False  True False]]


In [12]:
ans = a[bool_arr]
print(ans)

[25 24 29 26 26 28 26 21 27 26 22 25 28]


**Now lets try to set all the values which are greater than 20 as 100**

In [13]:
b = a
b[bool_arr] = 100
b

array([[100, 100, 100, 100, 100, 100],
       [ 20,  19,   6, 100,  11,   5],
       [  2, 100, 100,   8,   6, 100],
       [ 13,  12,  11,  16, 100,  18],
       [ 12, 100,  12,  13, 100,   6]])

**For this bool indexing to work in 2d array the dimension of bool array should be same as dimension of main array**

In [14]:
c = np.random.randint(1,10,(2,2))
c

array([[9, 6],
       [4, 5]])

In [15]:
bool_temp = np.array([[True,False],[True,True],[False,True]])
bool_temp

array([[ True, False],
       [ True,  True],
       [False,  True]])

In [16]:
c[bool_temp] = 7

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [17]:
print(a)

[[100 100 100 100 100 100]
 [ 20  19   6 100  11   5]
 [  2 100 100   8   6 100]
 [ 13  12  11  16 100  18]
 [ 12 100  12  13 100   6]]


**Lets say we want to update the third column of our array and set 99 wherever there is 100**

In [18]:
##first we will create the bool array
bool_ar = a[:,2] == 100
bool_ar

array([ True, False,  True, False, False])

**five elements are printed because 5 rows are there**

In [20]:
a[bool_ar,2] = 99
print(a)

[[100 100  99 100 100 100]
 [ 20  19   6 100  11   5]
 [  2 100  99   8   6 100]
 [ 13  12  11  16 100  18]
 [ 12 100  12  13 100   6]]


In [21]:
a[2,bool_ar] = 99
print(a)

IndexError: boolean index did not match indexed array along dimension 1; dimension is 6 but corresponding boolean dimension is 5

In [3]:
import numpy as np

arr = np.array([[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]])

sorted_arr = arr[arr[:,1].argsort()]
print(sorted_arr)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [2]:
import numpy as np

arr = np.array([1,2,5,3,4,7])
b = arr.argsort()
b

array([0, 1, 3, 4, 2, 5], dtype=int64)

**Now if we want to sort an array by a colum**

In [3]:
arr = np.array([[1,3,2,6],[15,16,18,25],[3,4,7,0],[3,17,18,21]])
print(arr)

[[ 1  3  2  6]
 [15 16 18 25]
 [ 3  4  7  0]
 [ 3 17 18 21]]


**we want to sort it by 2nd col**

In [4]:
##lets first print 2nd column
sec_col = arr[:,1]
print(sec_col)

[ 3 16  4 17]


In [5]:
#sorting second col
ind_col = sec_col.argsort()
print(ind_col)

[0 2 1 3]


In [6]:
#now we can sort all the rows based on this indices
arr = arr[ind_col]
print(arr)

[[ 1  3  2  6]
 [ 3  4  7  0]
 [15 16 18 25]
 [ 3 17 18 21]]


**Clubbing all the commands together**

In [7]:
k = np.array([[1,3,2,6],[15,16,18,25],[3,4,7,0],[3,17,18,21]])
sorted_array = k[k[:,1].argsort()]

In [9]:
sorted_array

array([[ 1,  3,  2,  6],
       [ 3,  4,  7,  0],
       [15, 16, 18, 25],
       [ 3, 17, 18, 21]])

**Sorting a array by row 1**

In [12]:
k = np.array([[1,3,2,6],[15,16,18,25],[3,4,7,0],[3,17,18,21]])

# first we will sort the first row and get its indices
ind = k[0].argsort()

#now giving this indices list to main array to sort it via column

sort_array = k[:,ind]
sort_array

array([[ 1,  2,  3,  6],
       [15, 18, 16, 25],
       [ 3,  7,  4,  0],
       [ 3, 18, 17, 21]])

**Clubbing all the commands together**

In [ ]:
sort_array = arr[:,arr[0].argsort()]